# Generated by Django 3.2.11 on 2022-01-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Restaurant Manager', 'Restaurant Manager'), ('***', '***')], default='Customer', max_length=18),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(default='images/ques.jpeg', upload_to='image_uploads'),
        ),
    ]
